# Generated by Django 4.2 on 2023-10-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0002_alter_mymessage_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='background_color',
            field=models.CharField(choices=[('green', 'Green'), ('red', 'Red'), ('#F0E68C', 'Yellow'), ('#A91101', 'Soft Red')], max_length=20),
        ),
    ]
