# Generated by Django 4.2 on 2023-10-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0008_alter_mymessage_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='status',
            field=models.CharField(choices=[('ledig', 'Ledig'), ('møte', 'Møte'), ('borte', 'Borte'), ('reise', 'Reise')], default='ledig', max_length=20),
        ),
    ]
