# Generated by Django 4.2 on 2023-10-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0009_mymessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='status',
            field=models.CharField(choices=[('ledig', 'Ledig'), ('møte', 'Møte'), ('borte', 'Borte'), ('reise', 'Reise'), ('', 'Tom')], default='ledig', max_length=20),
        ),
    ]
