# Generated by Django 4.2 on 2023-10-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0010_alter_mymessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='status',
            field=models.CharField(blank=True, choices=[('ledig', 'Ledig'), ('møte', 'Møte'), ('borte', 'Borte'), ('reise', 'Reise')], default='', max_length=20, null=True),
        ),
    ]
