# Generated by Django 4.2 on 2023-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0012_alter_mymessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='status',
            field=models.CharField(blank=True, choices=[('Ledig', 'Ledig'), ('Møte', 'Møte'), ('Ikke på kontoret', 'Ikke på kontoret'), ('Reise', 'Reise'), ('', 'No Status')], default='', max_length=20, null=True),
        ),
    ]
