# Generated by Django 4.2 on 2023-10-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0016_alter_mymessage_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
