# Generated by Django 5.0.2 on 2024-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0019_alter_mymessage_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='background_color',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('#A91101', 'Soft Red'), ('', 'No Color')], max_length=20, null=True),
        ),
    ]
