# Generated by Django 5.0.2 on 2024-03-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0022_alter_mymessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='background_image',
            field=models.CharField(blank=True, choices=[('flyingPlan.mp4', 'Reise'), ('Matrix.mp4', 'Kontoret'), ('meeting.mp4', 'Møte'), ('terminal.mp4', 'Terminal')], max_length=255, null=True),
        ),
    ]
